### ISSUE TITLE
[feature request]: Add Comment Feature

### ISSUE THREAD

**Issue by gyunseo** [pminsung12/minlog#2]
### Describe the bug

댓글 기능을 만들어 주세요.

### To reproduce

<https://www.giant-minsung.tech/Node-js-%EA%B0%9C%EB%85%90-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0>에 댓글을 달려고 했는데, 댓글 기능이 없습니다.

### Browser

Google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by pminsung12** [comment]
반영했습니다, 감사합니다!

[giant-minsung.tech](https://giant-minsung.tech)
